### ISSUE TITLE
Maine needs fix for new website

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#372]
I'm actually talking to the reporter of decisions in Maine and he wants to start uploading opinions directly, but before that can happen, he says it'd be better if we had all the historical stuff. Alas, they changed their website last year, and we dont' have anything since November or so. 

Any chance you can help with this, @arderyp ?

**Comment by arderyp** [comment]
@mlissner is this still the data?

https://www.courts.maine.gov/courts/sjc/opinions.html

If so, I don't think they really changed their site drastically, we just had a hiccup in our code, which I've just pushed a fix to.

**Comment by arderyp** [comment]
@mlissner @flooie, I believe this is fixed based on my comment above.  please reopen and @ me if not.

**Comment by flooie** [comment]
I think this is correct @arderyp - I added a simple back scraper for the 2017+ opinions that are currently online.

**Comment by flooie** [comment]
Okay this needs a small tweak.

**Comment by flooie** [comment]
The Maine back scraper was added - but the regular scraper was still failing to import.  I finally realized that 
1) The download paths were incorrect because they old URL was redirecting to a new opinions page.  The download paths were being built with the old URL and not the new one.  

Fix was simply updating the URL to the new opinions page directly.
